"""Expand the local demo POI dataset without calling external map APIs."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ROOT / "pois.json"


ADDITIONAL_POIS: list[dict[str, Any]] = [
    {"id": "gz-coffee-004", "name": "不打烊咖啡 东山口店", "category": "coffee", "sub_category": "neighborhood_cafe", "district": "越秀区", "city": "广州", "address": "广州市越秀区东山口周边", "latitude": 23.1227, "longitude": 113.2969, "price": 35, "visit_duration": 40, "rating": 4.3, "business_hours": "09:00-21:00", "tags": ["咖啡", "街区", "安静"], "suitable_for": ["独自", "朋友", "情侣"], "queue_level": 2, "photo_score": 4, "date_score": 3, "food_score": 3, "culture_score": 3, "local_feature_score": 3, "rainy_day_score": 4, "indoor_outdoor": "indoor", "description": "东山口街区里的轻量咖啡停靠点，适合短休息。"},
    {"id": "gz-coffee-005", "name": "沙面街角咖啡", "category": "coffee", "sub_category": "neighborhood_cafe", "district": "荔湾区", "city": "广州", "address": "广州市荔湾区沙面北街", "latitude": 23.1105, "longitude": 113.2401, "price": 39, "visit_duration": 45, "rating": 4.4, "business_hours": "10:00-20:30", "tags": ["咖啡", "沙面", "拍照", "休闲"], "suitable_for": ["情侣", "朋友", "独自"], "queue_level": 2, "photo_score": 5, "date_score": 4, "food_score": 3, "culture_score": 3, "local_feature_score": 4, "rainy_day_score": 4, "indoor_outdoor": "indoor", "description": "适合沙面散步前后的咖啡补给，空间不大。"},
    {"id": "gz-coffee-006", "name": "北京路小巷咖啡", "category": "coffee", "sub_category": "local_cafe", "district": "越秀区", "city": "广州", "address": "广州市越秀区北京路周边", "latitude": 23.1256, "longitude": 113.2702, "price": 32, "visit_duration": 35, "rating": 4.1, "business_hours": "09:30-22:00", "tags": ["咖啡", "小巷", "性价比"], "suitable_for": ["朋友", "独自"], "queue_level": 2, "photo_score": 3, "date_score": 3, "food_score": 3, "culture_score": 2, "local_feature_score": 3, "rainy_day_score": 4, "indoor_outdoor": "indoor", "description": "北京路附近的低预算咖啡点，适合快速衔接。"},
    {"id": "gz-food-006", "name": "点都德 聚福楼", "category": "food", "sub_category": "dim_sum", "district": "越秀区", "city": "广州", "address": "广州市越秀区惠福东路", "latitude": 23.1231, "longitude": 113.2692, "price": 85, "visit_duration": 75, "rating": 4.4, "business_hours": "08:00-22:00", "tags": ["早茶", "粤式点心", "本地特色"], "suitable_for": ["家庭", "朋友", "情侣"], "queue_level": 4, "photo_score": 2, "date_score": 3, "food_score": 5, "culture_score": 3, "local_feature_score": 5, "rainy_day_score": 4, "indoor_outdoor": "indoor", "description": "老城早茶代表点，饭点排队风险较高。"},
    {"id": "gz-food-007", "name": "南园酒家", "category": "food", "sub_category": "cantonese", "district": "海珠区", "city": "广州", "address": "广州市海珠区前进路", "latitude": 23.1036, "longitude": 113.2743, "price": 120, "visit_duration": 90, "rating": 4.5, "business_hours": "11:00-21:30", "tags": ["粤菜", "老字号", "正餐"], "suitable_for": ["家庭", "情侣", "朋友"], "queue_level": 3, "photo_score": 3, "date_score": 4, "food_score": 5, "culture_score": 3, "local_feature_score": 5, "rainy_day_score": 4, "indoor_outdoor": "indoor", "description": "更适合正式用餐的粤菜点，预算要求略高。"},
    {"id": "gz-food-008", "name": "阿婆牛杂 北京路店", "category": "food", "sub_category": "local_snack", "district": "越秀区", "city": "广州", "address": "广州市越秀区北京路附近", "latitude": 23.1242, "longitude": 113.2708, "price": 26, "visit_duration": 30, "rating": 4.1, "business_hours": "11:00-22:00", "tags": ["牛杂", "小吃", "本地味"], "suitable_for": ["朋友", "独自"], "queue_level": 3, "photo_score": 1, "date_score": 2, "food_score": 4, "culture_score": 2, "local_feature_score": 5, "rainy_day_score": 2, "indoor_outdoor": "outdoor", "description": "本地小吃型短停点，适合低预算路线穿插。"},
    {"id": "gz-exhibition-004", "name": "广州艺术博物院", "category": "exhibition", "sub_category": "art_museum", "district": "越秀区", "city": "广州", "address": "广州市越秀区麓湖路", "latitude": 23.1421, "longitude": 113.2891, "price": 0, "visit_duration": 90, "rating": 4.5, "business_hours": "09:00-17:00", "tags": ["艺术", "室内", "看展"], "suitable_for": ["独自", "朋友", "家庭"], "queue_level": 2, "photo_score": 3, "date_score": 3, "food_score": 1, "culture_score": 5, "local_feature_score": 4, "rainy_day_score": 5, "indoor_outdoor": "indoor", "description": "适合文化向和雨天路线的室内展览点。"},
    {"id": "gz-exhibition-005", "name": "T.I.T 创意园", "category": "exhibition", "sub_category": "creative_park", "district": "海珠区", "city": "广州", "address": "广州市海珠区新港中路397号", "latitude": 23.0989, "longitude": 113.3228, "price": 0, "visit_duration": 60, "rating": 4.2, "business_hours": "10:00-22:00", "tags": ["创意园", "拍照", "咖啡", "街区"], "suitable_for": ["朋友", "情侣", "独自"], "queue_level": 2, "photo_score": 4, "date_score": 3, "food_score": 2, "culture_score": 3, "local_feature_score": 3, "rainy_day_score": 2, "indoor_outdoor": "outdoor", "description": "轻量创意园点，适合和广州塔周边路线组合。"},
    {"id": "gz-museum-002", "name": "南越王博物院", "category": "museum", "sub_category": "history_museum", "district": "越秀区", "city": "广州", "address": "广州市越秀区解放北路", "latitude": 23.1412, "longitude": 113.2641, "price": 10, "visit_duration": 90, "rating": 4.6, "business_hours": "09:00-17:30", "tags": ["博物馆", "历史", "室内", "岭南"], "suitable_for": ["家庭", "独自", "朋友"], "queue_level": 2, "photo_score": 3, "date_score": 3, "food_score": 1, "culture_score": 5, "local_feature_score": 5, "rainy_day_score": 5, "indoor_outdoor": "indoor", "description": "历史内容稳定，适合文化和亲子路线。"},
    {"id": "gz-street-004", "name": "东山口街区", "category": "street", "sub_category": "historic_block", "district": "越秀区", "city": "广州", "address": "广州市越秀区东山口", "latitude": 23.1225, "longitude": 113.2976, "price": 0, "visit_duration": 70, "rating": 4.5, "business_hours": "00:00-23:59", "tags": ["citywalk", "洋楼", "拍照", "咖啡"], "suitable_for": ["情侣", "朋友", "独自"], "queue_level": 3, "photo_score": 5, "date_score": 4, "food_score": 2, "culture_score": 4, "local_feature_score": 4, "rainy_day_score": 2, "indoor_outdoor": "outdoor", "description": "广州热门 citywalk 区域，周末拍照点会比较拥挤。"},
    {"id": "gz-street-005", "name": "上下九步行街", "category": "street", "sub_category": "commercial_street", "district": "荔湾区", "city": "广州", "address": "广州市荔湾区上下九", "latitude": 23.1144, "longitude": 113.2481, "price": 0, "visit_duration": 60, "rating": 4.1, "business_hours": "10:00-22:30", "tags": ["步行街", "小吃", "热闹", "老城"], "suitable_for": ["朋友", "家庭"], "queue_level": 4, "photo_score": 3, "date_score": 2, "food_score": 4, "culture_score": 3, "local_feature_score": 4, "rainy_day_score": 2, "indoor_outdoor": "outdoor", "description": "老牌商业步行街，便利但高峰期拥挤。"},
    {"id": "gz-street-006", "name": "沿江西路骑楼街区", "category": "street", "sub_category": "river_street", "district": "越秀区", "city": "广州", "address": "广州市越秀区沿江西路", "latitude": 23.1137, "longitude": 113.2635, "price": 0, "visit_duration": 50, "rating": 4.3, "business_hours": "00:00-23:59", "tags": ["骑楼", "江边", "散步", "本地特色"], "suitable_for": ["朋友", "独自", "情侣"], "queue_level": 2, "photo_score": 4, "date_score": 3, "food_score": 1, "culture_score": 4, "local_feature_score": 5, "rainy_day_score": 2, "indoor_outdoor": "outdoor", "description": "更偏城市纹理的江边街区点，适合慢走。"},
    {"id": "gz-park-003", "name": "麓湖公园", "category": "park", "sub_category": "urban_park", "district": "越秀区", "city": "广州", "address": "广州市越秀区麓湖路", "latitude": 23.1465, "longitude": 113.2872, "price": 0, "visit_duration": 55, "rating": 4.4, "business_hours": "06:00-22:00", "tags": ["公园", "散步", "安静", "湖边"], "suitable_for": ["家庭", "情侣", "独自"], "queue_level": 1, "photo_score": 3, "date_score": 4, "food_score": 1, "culture_score": 2, "local_feature_score": 3, "rainy_day_score": 1, "indoor_outdoor": "outdoor", "description": "适合放慢节奏的公园点，天气不好时不建议久留。"},
    {"id": "gz-park-004", "name": "白云山南门", "category": "park", "sub_category": "mountain_park", "district": "白云区", "city": "广州", "address": "广州市白云区白云山南门", "latitude": 23.1632, "longitude": 113.2979, "price": 5, "visit_duration": 120, "rating": 4.6, "business_hours": "06:00-22:00", "tags": ["户外", "登高", "城市景观"], "suitable_for": ["朋友", "家庭"], "queue_level": 2, "photo_score": 4, "date_score": 3, "food_score": 1, "culture_score": 2, "local_feature_score": 4, "rainy_day_score": 1, "indoor_outdoor": "outdoor", "description": "体力消耗较高的户外点，只适合时间充裕的路线。"},
    {"id": "gz-night-003", "name": "珠江夜游天字码头", "category": "night", "sub_category": "river_cruise", "district": "越秀区", "city": "广州", "address": "广州市越秀区沿江中路天字码头", "latitude": 23.1182, "longitude": 113.2705, "price": 98, "visit_duration": 75, "rating": 4.3, "business_hours": "18:30-22:30", "tags": ["夜景", "珠江", "游船", "情侣"], "suitable_for": ["情侣", "朋友", "家庭"], "queue_level": 3, "photo_score": 5, "date_score": 5, "food_score": 1, "culture_score": 2, "local_feature_score": 4, "rainy_day_score": 2, "indoor_outdoor": "outdoor", "description": "夜景记忆点强，但预算和时段约束更明显。"},
    {"id": "gz-night-004", "name": "广州塔广场夜景", "category": "night", "sub_category": "landmark_night_view", "district": "海珠区", "city": "广州", "address": "广州市海珠区广州塔广场", "latitude": 23.1091, "longitude": 113.3244, "price": 0, "visit_duration": 45, "rating": 4.7, "business_hours": "18:00-23:59", "tags": ["广州塔", "夜景", "拍照", "地标"], "suitable_for": ["情侣", "朋友", "家庭"], "queue_level": 3, "photo_score": 5, "date_score": 4, "food_score": 1, "culture_score": 1, "local_feature_score": 4, "rainy_day_score": 1, "indoor_outdoor": "outdoor", "description": "广州地标夜景点，适合路线收尾但人流集中。"},
    {"id": "gz-shopping-003", "name": "K11购物艺术中心 广州", "category": "shopping", "sub_category": "art_mall", "district": "天河区", "city": "广州", "address": "广州市天河区珠江东路6号", "latitude": 23.1186, "longitude": 113.3293, "price": 0, "visit_duration": 75, "rating": 4.5, "business_hours": "10:00-22:00", "tags": ["商场", "艺术", "室内", "餐饮"], "suitable_for": ["情侣", "朋友", "独自"], "queue_level": 3, "photo_score": 4, "date_score": 4, "food_score": 3, "culture_score": 3, "local_feature_score": 2, "rainy_day_score": 5, "indoor_outdoor": "indoor", "description": "珠江新城室内商业点，适合雨天和约会兜底。"},
    {"id": "gz-shopping-004", "name": "正佳广场", "category": "shopping", "sub_category": "mall", "district": "天河区", "city": "广州", "address": "广州市天河区天河路228号", "latitude": 23.1327, "longitude": 113.3272, "price": 0, "visit_duration": 85, "rating": 4.4, "business_hours": "10:00-22:00", "tags": ["商场", "餐饮", "亲子", "室内"], "suitable_for": ["家庭", "朋友", "情侣"], "queue_level": 4, "photo_score": 3, "date_score": 3, "food_score": 4, "culture_score": 1, "local_feature_score": 2, "rainy_day_score": 5, "indoor_outdoor": "indoor", "description": "功能完整但人流较大的室内商场点。"},
    {"id": "gz-scene-002", "name": "越秀公园镇海楼", "category": "scene", "sub_category": "historic_site", "district": "越秀区", "city": "广州", "address": "广州市越秀区越秀公园内", "latitude": 23.1397, "longitude": 113.2643, "price": 0, "visit_duration": 70, "rating": 4.5, "business_hours": "06:00-22:00", "tags": ["历史", "公园", "拍照", "本地特色"], "suitable_for": ["家庭", "朋友", "独自"], "queue_level": 2, "photo_score": 4, "date_score": 3, "food_score": 1, "culture_score": 5, "local_feature_score": 5, "rainy_day_score": 2, "indoor_outdoor": "outdoor", "description": "历史和公园属性兼具，适合文化轻徒步路线。"},
    {"id": "sh-coffee-004", "name": "Manner Coffee 武康路店", "category": "coffee", "sub_category": "specialty_coffee", "district": "徐汇区", "city": "上海", "address": "上海市徐汇区武康路周边", "latitude": 31.2059, "longitude": 121.4392, "price": 25, "visit_duration": 30, "rating": 4.2, "business_hours": "08:00-20:00", "tags": ["咖啡", "街区", "性价比"], "suitable_for": ["独自", "朋友"], "queue_level": 3, "photo_score": 3, "date_score": 3, "food_score": 3, "culture_score": 2, "local_feature_score": 2, "rainy_day_score": 3, "indoor_outdoor": "indoor", "description": "适合快速补咖啡的低预算点，高峰时段等候会增加。"},
    {"id": "sh-coffee-005", "name": "Blue Bottle 张园店", "category": "coffee", "sub_category": "specialty_coffee", "district": "静安区", "city": "上海", "address": "上海市静安区张园", "latitude": 31.2288, "longitude": 121.4601, "price": 48, "visit_duration": 45, "rating": 4.4, "business_hours": "08:00-21:00", "tags": ["咖啡", "张园", "拍照", "热门"], "suitable_for": ["情侣", "朋友", "独自"], "queue_level": 4, "photo_score": 5, "date_score": 4, "food_score": 3, "culture_score": 3, "local_feature_score": 2, "rainy_day_score": 4, "indoor_outdoor": "indoor", "description": "拍照和品牌识别度高，但热门时段排队明显。"},
    {"id": "sh-coffee-006", "name": "太原路小院咖啡", "category": "coffee", "sub_category": "neighborhood_cafe", "district": "徐汇区", "city": "上海", "address": "上海市徐汇区太原路", "latitude": 31.2102, "longitude": 121.4541, "price": 43, "visit_duration": 45, "rating": 4.5, "business_hours": "09:00-19:00", "tags": ["咖啡", "安静", "小院", "街区"], "suitable_for": ["独自", "情侣", "朋友"], "queue_level": 2, "photo_score": 4, "date_score": 4, "food_score": 3, "culture_score": 3, "local_feature_score": 3, "rainy_day_score": 4, "indoor_outdoor": "indoor", "description": "更安静的街区咖啡点，适合慢节奏路线。"},
    {"id": "sh-food-005", "name": "佳家汤包 黄河路店", "category": "food", "sub_category": "shanghai_snacks", "district": "黄浦区", "city": "上海", "address": "上海市黄浦区黄河路", "latitude": 31.2368, "longitude": 121.4702, "price": 38, "visit_duration": 40, "rating": 4.4, "business_hours": "07:00-20:00", "tags": ["小笼", "本地小吃", "性价比"], "suitable_for": ["独自", "朋友"], "queue_level": 4, "photo_score": 2, "date_score": 2, "food_score": 5, "culture_score": 3, "local_feature_score": 5, "rainy_day_score": 3, "indoor_outdoor": "indoor", "description": "高性价比小吃点，但排队风险明显。"},
    {"id": "sh-food-006", "name": "兰心餐厅", "category": "food", "sub_category": "shanghai_cuisine", "district": "黄浦区", "city": "上海", "address": "上海市黄浦区进贤路", "latitude": 31.2242, "longitude": 121.4637, "price": 95, "visit_duration": 75, "rating": 4.4, "business_hours": "11:00-21:00", "tags": ["本帮菜", "小馆", "本地特色"], "suitable_for": ["朋友", "情侣"], "queue_level": 4, "photo_score": 2, "date_score": 3, "food_score": 5, "culture_score": 3, "local_feature_score": 5, "rainy_day_score": 3, "indoor_outdoor": "indoor", "description": "本帮小馆代表，位置方便但不适合赶时间。"},
    {"id": "sh-food-007", "name": "大壶春 四川中路店", "category": "food", "sub_category": "shanghai_snacks", "district": "黄浦区", "city": "上海", "address": "上海市黄浦区四川中路", "latitude": 31.2371, "longitude": 121.4838, "price": 30, "visit_duration": 35, "rating": 4.2, "business_hours": "06:30-20:30", "tags": ["生煎", "本地小吃", "性价比"], "suitable_for": ["独自", "朋友", "家庭"], "queue_level": 3, "photo_score": 2, "date_score": 2, "food_score": 4, "culture_score": 3, "local_feature_score": 5, "rainy_day_score": 3, "indoor_outdoor": "indoor", "description": "适合预算友好路线的短停小吃点。"},
    {"id": "sh-food-008", "name": "人和馆 肇嘉浜路店", "category": "food", "sub_category": "shanghai_cuisine", "district": "徐汇区", "city": "上海", "address": "上海市徐汇区肇嘉浜路", "latitude": 31.1995, "longitude": 121.4439, "price": 110, "visit_duration": 85, "rating": 4.5, "business_hours": "11:00-21:30", "tags": ["本帮菜", "正餐", "约会"], "suitable_for": ["情侣", "家庭", "朋友"], "queue_level": 3, "photo_score": 3, "date_score": 4, "food_score": 5, "culture_score": 3, "local_feature_score": 4, "rainy_day_score": 4, "indoor_outdoor": "indoor", "description": "更适合正式正餐的本帮菜点，预算要求偏高。"},
    {"id": "sh-exhibition-003", "name": "龙美术馆 西岸馆", "category": "exhibition", "sub_category": "art_museum", "district": "徐汇区", "city": "上海", "address": "上海市徐汇区龙腾大道", "latitude": 31.1858, "longitude": 121.4629, "price": 100, "visit_duration": 100, "rating": 4.6, "business_hours": "10:00-17:30", "tags": ["看展", "艺术", "西岸", "室内"], "suitable_for": ["情侣", "朋友", "独自"], "queue_level": 2, "photo_score": 4, "date_score": 4, "food_score": 1, "culture_score": 5, "local_feature_score": 3, "rainy_day_score": 5, "indoor_outdoor": "indoor", "description": "西岸艺术路线主站，票价和展期需要提前确认。"},
    {"id": "sh-exhibition-004", "name": "浦东美术馆", "category": "exhibition", "sub_category": "art_museum", "district": "浦东新区", "city": "上海", "address": "上海市浦东新区滨江大道", "latitude": 31.2391, "longitude": 121.5022, "price": 120, "visit_duration": 100, "rating": 4.6, "business_hours": "10:00-21:00", "tags": ["美术馆", "室内", "江景", "拍照"], "suitable_for": ["情侣", "朋友", "独自"], "queue_level": 3, "photo_score": 5, "date_score": 4, "food_score": 1, "culture_score": 5, "local_feature_score": 3, "rainy_day_score": 5, "indoor_outdoor": "indoor", "description": "兼具展览和江景视角，预算和客流都需要考虑。"},
    {"id": "sh-museum-003", "name": "上海自然博物馆", "category": "museum", "sub_category": "science_museum", "district": "静安区", "city": "上海", "address": "上海市静安区北京西路510号", "latitude": 31.2365, "longitude": 121.4627, "price": 30, "visit_duration": 120, "rating": 4.7, "business_hours": "09:00-17:00", "tags": ["博物馆", "亲子", "室内", "科普"], "suitable_for": ["家庭", "朋友"], "queue_level": 4, "photo_score": 3, "date_score": 2, "food_score": 1, "culture_score": 5, "local_feature_score": 3, "rainy_day_score": 5, "indoor_outdoor": "indoor", "description": "亲子和科普属性强，但节假日排队压力较大。"},
    {"id": "sh-street-004", "name": "思南路街区", "category": "street", "sub_category": "historic_street", "district": "黄浦区", "city": "上海", "address": "上海市黄浦区思南路", "latitude": 31.2148, "longitude": 121.4661, "price": 0, "visit_duration": 60, "rating": 4.6, "business_hours": "00:00-23:59", "tags": ["街区", "洋房", "citywalk", "拍照"], "suitable_for": ["情侣", "朋友", "独自"], "queue_level": 2, "photo_score": 5, "date_score": 4, "food_score": 2, "culture_score": 4, "local_feature_score": 4, "rainy_day_score": 2, "indoor_outdoor": "outdoor", "description": "适合慢走和拍建筑的街区点，雨天体验一般。"},
    {"id": "sh-street-005", "name": "巨鹿路街区", "category": "street", "sub_category": "lifestyle_street", "district": "静安区", "city": "上海", "address": "上海市静安区巨鹿路", "latitude": 31.2222, "longitude": 121.4551, "price": 0, "visit_duration": 55, "rating": 4.4, "business_hours": "10:00-22:00", "tags": ["街区", "小店", "咖啡", "夜晚"], "suitable_for": ["朋友", "情侣", "独自"], "queue_level": 3, "photo_score": 4, "date_score": 4, "food_score": 2, "culture_score": 3, "local_feature_score": 3, "rainy_day_score": 2, "indoor_outdoor": "outdoor", "description": "适合朋友下班后轻逛，商业化程度中等。"},
    {"id": "sh-street-006", "name": "大学路街区", "category": "street", "sub_category": "youth_street", "district": "杨浦区", "city": "上海", "address": "上海市杨浦区大学路", "latitude": 31.3069, "longitude": 121.5124, "price": 0, "visit_duration": 60, "rating": 4.3, "business_hours": "10:00-22:00", "tags": ["街区", "咖啡", "学生", "小店"], "suitable_for": ["朋友", "独自"], "queue_level": 2, "photo_score": 4, "date_score": 3, "food_score": 3, "culture_score": 3, "local_feature_score": 3, "rainy_day_score": 2, "indoor_outdoor": "outdoor", "description": "更适合杨浦附近路线，距离市中心路线较远。"},
    {"id": "sh-park-003", "name": "静安雕塑公园", "category": "park", "sub_category": "urban_park", "district": "静安区", "city": "上海", "address": "上海市静安区石门二路", "latitude": 31.2364, "longitude": 121.4652, "price": 0, "visit_duration": 45, "rating": 4.5, "business_hours": "05:00-22:00", "tags": ["公园", "雕塑", "安静", "亲子"], "suitable_for": ["家庭", "独自", "情侣"], "queue_level": 1, "photo_score": 4, "date_score": 4, "food_score": 1, "culture_score": 3, "local_feature_score": 3, "rainy_day_score": 1, "indoor_outdoor": "outdoor", "description": "市中心低成本缓冲点，适合降低路线强度。"},
    {"id": "sh-park-004", "name": "世纪公园", "category": "park", "sub_category": "large_park", "district": "浦东新区", "city": "上海", "address": "上海市浦东新区锦绣路", "latitude": 31.2151, "longitude": 121.5505, "price": 0, "visit_duration": 100, "rating": 4.6, "business_hours": "06:00-18:00", "tags": ["公园", "亲子", "户外", "大面积"], "suitable_for": ["家庭", "朋友"], "queue_level": 2, "photo_score": 4, "date_score": 3, "food_score": 1, "culture_score": 1, "local_feature_score": 2, "rainy_day_score": 1, "indoor_outdoor": "outdoor", "description": "大体量公园点，适合亲子和半日户外，但转场成本较高。"},
    {"id": "sh-night-003", "name": "苏州河外白渡桥", "category": "night", "sub_category": "bridge_night_view", "district": "虹口区", "city": "上海", "address": "上海市虹口区外白渡桥", "latitude": 31.2466, "longitude": 121.4902, "price": 0, "visit_duration": 40, "rating": 4.6, "business_hours": "00:00-23:59", "tags": ["夜景", "桥", "拍照", "历史"], "suitable_for": ["情侣", "朋友", "独自"], "queue_level": 2, "photo_score": 5, "date_score": 4, "food_score": 1, "culture_score": 4, "local_feature_score": 4, "rainy_day_score": 1, "indoor_outdoor": "outdoor", "description": "夜景和历史感兼具的短停点，适合外滩附近路线。"},
    {"id": "sh-night-004", "name": "徐家汇天桥夜景", "category": "night", "sub_category": "urban_night_view", "district": "徐汇区", "city": "上海", "address": "上海市徐汇区徐家汇商圈", "latitude": 31.1943, "longitude": 121.4371, "price": 0, "visit_duration": 35, "rating": 4.2, "business_hours": "18:00-23:00", "tags": ["夜景", "商圈", "拍照", "短停"], "suitable_for": ["朋友", "独自", "情侣"], "queue_level": 2, "photo_score": 4, "date_score": 3, "food_score": 1, "culture_score": 1, "local_feature_score": 2, "rainy_day_score": 1, "indoor_outdoor": "outdoor", "description": "适合徐汇路线短暂收尾，地标感不如外滩强。"},
    {"id": "sh-shopping-003", "name": "TX淮海", "category": "shopping", "sub_category": "youth_mall", "district": "黄浦区", "city": "上海", "address": "上海市黄浦区淮海中路523号", "latitude": 31.2211, "longitude": 121.4661, "price": 0, "visit_duration": 65, "rating": 4.3, "business_hours": "10:00-22:00", "tags": ["商场", "潮流", "室内", "拍照"], "suitable_for": ["朋友", "独自", "情侣"], "queue_level": 3, "photo_score": 4, "date_score": 3, "food_score": 3, "culture_score": 2, "local_feature_score": 2, "rainy_day_score": 5, "indoor_outdoor": "indoor", "description": "更偏年轻化的室内商业点，适合雨天和朋友局。"},
    {"id": "sh-scene-002", "name": "东方明珠城市广场", "category": "scene", "sub_category": "landmark", "district": "浦东新区", "city": "上海", "address": "上海市浦东新区世纪大道1号", "latitude": 31.2397, "longitude": 121.4998, "price": 0, "visit_duration": 45, "rating": 4.6, "business_hours": "00:00-23:59", "tags": ["地标", "拍照", "陆家嘴", "游客"], "suitable_for": ["家庭", "情侣", "朋友"], "queue_level": 4, "photo_score": 5, "date_score": 4, "food_score": 1, "culture_score": 2, "local_feature_score": 4, "rainy_day_score": 2, "indoor_outdoor": "outdoor", "description": "地标识别度高，但游客密度和商业化程度都较高。"},
]


SECOND_WAVE_POIS: list[dict[str, Any]] = [
    {"id": "gz-coffee-007", "name": "荔湾桥边咖啡", "category": "coffee", "sub_category": "local_cafe", "district": "荔湾区", "city": "广州", "address": "广州市荔湾区泮塘路周边", "latitude": 23.1218, "longitude": 113.2394, "price": 34, "visit_duration": 40, "rating": 4.2, "business_hours": "09:30-21:00", "tags": ["咖啡", "荔湾", "安静", "休息"], "suitable_for": ["独自", "朋友"], "queue_level": 2, "photo_score": 3, "date_score": 3, "food_score": 3, "culture_score": 3, "local_feature_score": 4, "rainy_day_score": 4, "indoor_outdoor": "indoor", "description": "老城附近的轻量咖啡停靠点，适合路线中途降强度。"},
    {"id": "gz-coffee-008", "name": "珠江新城轻咖", "category": "coffee", "sub_category": "business_cafe", "district": "天河区", "city": "广州", "address": "广州市天河区珠江新城周边", "latitude": 23.1203, "longitude": 113.3228, "price": 45, "visit_duration": 45, "rating": 4.3, "business_hours": "08:30-20:30", "tags": ["咖啡", "商圈", "室内", "商务"], "suitable_for": ["独自", "朋友", "情侣"], "queue_level": 3, "photo_score": 3, "date_score": 3, "food_score": 3, "culture_score": 2, "local_feature_score": 2, "rainy_day_score": 5, "indoor_outdoor": "indoor", "description": "商圈内稳定的室内休息点，适合雨天兜底。"},
    {"id": "gz-coffee-009", "name": "海珠社区咖啡角", "category": "coffee", "sub_category": "community_cafe", "district": "海珠区", "city": "广州", "address": "广州市海珠区江南西周边", "latitude": 23.0958, "longitude": 113.2748, "price": 29, "visit_duration": 35, "rating": 4.1, "business_hours": "10:00-22:00", "tags": ["咖啡", "社区", "性价比"], "suitable_for": ["朋友", "独自"], "queue_level": 2, "photo_score": 2, "date_score": 2, "food_score": 3, "culture_score": 2, "local_feature_score": 3, "rainy_day_score": 4, "indoor_outdoor": "indoor", "description": "预算友好型咖啡点，不适合专程打卡但适合顺路。"},
    {"id": "gz-food-009", "name": "西关糖水铺", "category": "food", "sub_category": "dessert", "district": "荔湾区", "city": "广州", "address": "广州市荔湾区多宝路周边", "latitude": 23.1172, "longitude": 113.2451, "price": 24, "visit_duration": 30, "rating": 4.2, "business_hours": "12:00-23:00", "tags": ["糖水", "小吃", "本地味", "性价比"], "suitable_for": ["朋友", "家庭", "独自"], "queue_level": 3, "photo_score": 2, "date_score": 2, "food_score": 4, "culture_score": 2, "local_feature_score": 5, "rainy_day_score": 3, "indoor_outdoor": "indoor", "description": "短停型甜品小吃点，适合低预算老城路线。"},
    {"id": "gz-food-010", "name": "东山口简餐小馆", "category": "food", "sub_category": "casual_dining", "district": "越秀区", "city": "广州", "address": "广州市越秀区东山口周边", "latitude": 23.1231, "longitude": 113.2962, "price": 58, "visit_duration": 55, "rating": 4.2, "business_hours": "11:00-21:00", "tags": ["简餐", "街区", "朋友"], "suitable_for": ["朋友", "情侣", "独自"], "queue_level": 2, "photo_score": 3, "date_score": 3, "food_score": 4, "culture_score": 2, "local_feature_score": 3, "rainy_day_score": 4, "indoor_outdoor": "indoor", "description": "适合 citywalk 中穿插的正餐替代点，强度较低。"},
    {"id": "gz-food-011", "name": "海珠夜市小吃档", "category": "food", "sub_category": "night_snack", "district": "海珠区", "city": "广州", "address": "广州市海珠区客村周边", "latitude": 23.0998, "longitude": 113.3182, "price": 42, "visit_duration": 45, "rating": 4.0, "business_hours": "17:30-23:30", "tags": ["夜宵", "小吃", "热闹"], "suitable_for": ["朋友", "独自"], "queue_level": 4, "photo_score": 2, "date_score": 2, "food_score": 4, "culture_score": 2, "local_feature_score": 4, "rainy_day_score": 1, "indoor_outdoor": "outdoor", "description": "更适合朋友夜间路线，排队和天气风险较明显。"},
    {"id": "gz-food-012", "name": "天河轻食饭堂", "category": "food", "sub_category": "light_meal", "district": "天河区", "city": "广州", "address": "广州市天河区体育西周边", "latitude": 23.1319, "longitude": 113.3211, "price": 46, "visit_duration": 45, "rating": 4.1, "business_hours": "10:30-21:30", "tags": ["轻食", "商圈", "效率"], "suitable_for": ["独自", "朋友"], "queue_level": 2, "photo_score": 2, "date_score": 2, "food_score": 3, "culture_score": 1, "local_feature_score": 1, "rainy_day_score": 5, "indoor_outdoor": "indoor", "description": "商圈内高效率用餐点，适合预算和时间都有限的路线。"},
    {"id": "gz-exhibition-006", "name": "海珠小型影像空间", "category": "exhibition", "sub_category": "photo_gallery", "district": "海珠区", "city": "广州", "address": "广州市海珠区昌岗周边", "latitude": 23.0968, "longitude": 113.2815, "price": 30, "visit_duration": 55, "rating": 4.2, "business_hours": "11:00-19:00", "tags": ["影像", "看展", "室内", "小众"], "suitable_for": ["独自", "朋友", "情侣"], "queue_level": 1, "photo_score": 4, "date_score": 3, "food_score": 1, "culture_score": 4, "local_feature_score": 3, "rainy_day_score": 5, "indoor_outdoor": "indoor", "description": "小体量展览点，适合雨天或文艺路线补充。"},
    {"id": "gz-exhibition-007", "name": "东山口社区艺术站", "category": "exhibition", "sub_category": "community_art", "district": "越秀区", "city": "广州", "address": "广州市越秀区东山口街区", "latitude": 23.1214, "longitude": 113.2984, "price": 0, "visit_duration": 45, "rating": 4.1, "business_hours": "10:00-18:00", "tags": ["社区", "艺术", "街区", "短停"], "suitable_for": ["朋友", "独自"], "queue_level": 1, "photo_score": 3, "date_score": 3, "food_score": 1, "culture_score": 4, "local_feature_score": 4, "rainy_day_score": 3, "indoor_outdoor": "indoor", "description": "适合和东山口街区组合的小型文化点。"},
    {"id": "gz-museum-003", "name": "岭南生活博物馆", "category": "museum", "sub_category": "local_history", "district": "荔湾区", "city": "广州", "address": "广州市荔湾区恩宁路周边", "latitude": 23.1179, "longitude": 113.2489, "price": 15, "visit_duration": 70, "rating": 4.3, "business_hours": "09:30-17:30", "tags": ["博物馆", "岭南", "室内", "亲子"], "suitable_for": ["家庭", "独自", "朋友"], "queue_level": 2, "photo_score": 3, "date_score": 2, "food_score": 1, "culture_score": 5, "local_feature_score": 5, "rainy_day_score": 5, "indoor_outdoor": "indoor", "description": "模拟本地生活主题博物馆，适合亲子和文化向路线。"},
    {"id": "gz-museum-004", "name": "海珠工业记忆馆", "category": "museum", "sub_category": "industrial_museum", "district": "海珠区", "city": "广州", "address": "广州市海珠区工业大道周边", "latitude": 23.0832, "longitude": 113.2794, "price": 0, "visit_duration": 65, "rating": 4.1, "business_hours": "10:00-17:00", "tags": ["工业", "博物馆", "室内", "小众"], "suitable_for": ["朋友", "独自"], "queue_level": 1, "photo_score": 3, "date_score": 2, "food_score": 1, "culture_score": 4, "local_feature_score": 4, "rainy_day_score": 5, "indoor_outdoor": "indoor", "description": "更小众的室内文化点，适合差异化路线。"},
    {"id": "gz-street-007", "name": "泮塘老街", "category": "street", "sub_category": "old_town_street", "district": "荔湾区", "city": "广州", "address": "广州市荔湾区泮塘周边", "latitude": 23.1235, "longitude": 113.2366, "price": 0, "visit_duration": 55, "rating": 4.3, "business_hours": "00:00-23:59", "tags": ["老街", "本地特色", "散步"], "suitable_for": ["朋友", "独自", "家庭"], "queue_level": 2, "photo_score": 3, "date_score": 3, "food_score": 3, "culture_score": 4, "local_feature_score": 5, "rainy_day_score": 2, "indoor_outdoor": "outdoor", "description": "比热门街区更安静的老城步行点。"},
    {"id": "gz-street-008", "name": "江南西小店街区", "category": "street", "sub_category": "lifestyle_street", "district": "海珠区", "city": "广州", "address": "广州市海珠区江南西", "latitude": 23.0942, "longitude": 113.2732, "price": 0, "visit_duration": 60, "rating": 4.2, "business_hours": "10:00-22:30", "tags": ["小店", "咖啡", "朋友", "citywalk"], "suitable_for": ["朋友", "独自", "情侣"], "queue_level": 3, "photo_score": 3, "date_score": 3, "food_score": 3, "culture_score": 2, "local_feature_score": 3, "rainy_day_score": 2, "indoor_outdoor": "outdoor", "description": "适合朋友轻逛和临时加餐，周末略拥挤。"},
    {"id": "gz-street-009", "name": "体育西夜间街区", "category": "street", "sub_category": "business_street", "district": "天河区", "city": "广州", "address": "广州市天河区体育西路", "latitude": 23.1324, "longitude": 113.3219, "price": 0, "visit_duration": 45, "rating": 4.0, "business_hours": "17:00-23:30", "tags": ["夜晚", "商圈", "小店"], "suitable_for": ["朋友", "独自"], "queue_level": 4, "photo_score": 2, "date_score": 2, "food_score": 3, "culture_score": 1, "local_feature_score": 2, "rainy_day_score": 2, "indoor_outdoor": "outdoor", "description": "更偏下班后短逛，商业化和人流都偏高。"},
    {"id": "gz-park-005", "name": "二沙岛江边绿地", "category": "park", "sub_category": "riverside_green", "district": "越秀区", "city": "广州", "address": "广州市越秀区二沙岛周边", "latitude": 23.1131, "longitude": 113.3058, "price": 0, "visit_duration": 50, "rating": 4.5, "business_hours": "06:00-23:00", "tags": ["江边", "散步", "夜景", "放松"], "suitable_for": ["情侣", "朋友", "家庭"], "queue_level": 2, "photo_score": 4, "date_score": 4, "food_score": 1, "culture_score": 2, "local_feature_score": 3, "rainy_day_score": 1, "indoor_outdoor": "outdoor", "description": "适合降低路线强度的江边绿地，雨天不建议安排。"},
    {"id": "gz-park-006", "name": "海珠湿地北门", "category": "park", "sub_category": "wetland", "district": "海珠区", "city": "广州", "address": "广州市海珠区海珠湿地北门", "latitude": 23.0719, "longitude": 113.3348, "price": 20, "visit_duration": 90, "rating": 4.4, "business_hours": "09:00-18:00", "tags": ["湿地", "户外", "亲子", "自然"], "suitable_for": ["家庭", "朋友"], "queue_level": 2, "photo_score": 4, "date_score": 3, "food_score": 1, "culture_score": 1, "local_feature_score": 3, "rainy_day_score": 1, "indoor_outdoor": "outdoor", "description": "自然属性强但转场成本高，适合时间充裕路线。"},
    {"id": "gz-night-005", "name": "海心沙夜景平台", "category": "night", "sub_category": "river_night_view", "district": "天河区", "city": "广州", "address": "广州市天河区海心沙", "latitude": 23.1122, "longitude": 113.3226, "price": 0, "visit_duration": 45, "rating": 4.6, "business_hours": "18:00-23:30", "tags": ["夜景", "珠江", "拍照", "情侣"], "suitable_for": ["情侣", "朋友", "家庭"], "queue_level": 3, "photo_score": 5, "date_score": 5, "food_score": 1, "culture_score": 2, "local_feature_score": 4, "rainy_day_score": 1, "indoor_outdoor": "outdoor", "description": "适合珠江新城路线收尾，节假日人流偏高。"},
    {"id": "gz-night-006", "name": "西堤码头夜色", "category": "night", "sub_category": "old_river_night", "district": "荔湾区", "city": "广州", "address": "广州市荔湾区西堤周边", "latitude": 23.1099, "longitude": 113.2524, "price": 0, "visit_duration": 40, "rating": 4.2, "business_hours": "18:00-23:00", "tags": ["夜景", "老城", "江边", "散步"], "suitable_for": ["朋友", "情侣", "独自"], "queue_level": 2, "photo_score": 4, "date_score": 3, "food_score": 1, "culture_score": 3, "local_feature_score": 4, "rainy_day_score": 1, "indoor_outdoor": "outdoor", "description": "比广州塔区域更松弛的老城夜景短停点。"},
    {"id": "gz-shopping-005", "name": "江南西室内生活馆", "category": "shopping", "sub_category": "neighborhood_mall", "district": "海珠区", "city": "广州", "address": "广州市海珠区江南西周边", "latitude": 23.0952, "longitude": 113.2741, "price": 0, "visit_duration": 60, "rating": 4.1, "business_hours": "10:00-22:00", "tags": ["商场", "室内", "餐饮", "社区"], "suitable_for": ["朋友", "家庭"], "queue_level": 3, "photo_score": 2, "date_score": 2, "food_score": 4, "culture_score": 1, "local_feature_score": 2, "rainy_day_score": 5, "indoor_outdoor": "indoor", "description": "不强打卡但功能稳定，适合雨天和亲子路线兜底。"},
    {"id": "gz-scene-003", "name": "海珠桥城市视角", "category": "scene", "sub_category": "urban_view", "district": "越秀区", "city": "广州", "address": "广州市越秀区海珠桥周边", "latitude": 23.1166, "longitude": 113.2658, "price": 0, "visit_duration": 30, "rating": 4.1, "business_hours": "00:00-23:59", "tags": ["桥", "城市景观", "短停", "拍照"], "suitable_for": ["朋友", "独自"], "queue_level": 2, "photo_score": 4, "date_score": 2, "food_score": 1, "culture_score": 3, "local_feature_score": 4, "rainy_day_score": 1, "indoor_outdoor": "outdoor", "description": "适合老城路线中的短暂停靠，不适合作为主站。"},
    {"id": "sh-coffee-007", "name": "衡山路街角咖啡", "category": "coffee", "sub_category": "neighborhood_cafe", "district": "徐汇区", "city": "上海", "address": "上海市徐汇区衡山路周边", "latitude": 31.2035, "longitude": 121.4475, "price": 42, "visit_duration": 45, "rating": 4.3, "business_hours": "09:00-21:00", "tags": ["咖啡", "街区", "安静"], "suitable_for": ["情侣", "独自", "朋友"], "queue_level": 2, "photo_score": 4, "date_score": 4, "food_score": 3, "culture_score": 3, "local_feature_score": 3, "rainy_day_score": 4, "indoor_outdoor": "indoor", "description": "适合徐汇街区路线中段休息，氛围较松弛。"},
    {"id": "sh-coffee-008", "name": "北外滩小窗咖啡", "category": "coffee", "sub_category": "river_cafe", "district": "虹口区", "city": "上海", "address": "上海市虹口区北外滩周边", "latitude": 31.2491, "longitude": 121.4972, "price": 46, "visit_duration": 40, "rating": 4.2, "business_hours": "09:30-20:30", "tags": ["咖啡", "江景", "拍照"], "suitable_for": ["朋友", "情侣", "独自"], "queue_level": 3, "photo_score": 4, "date_score": 4, "food_score": 3, "culture_score": 2, "local_feature_score": 2, "rainy_day_score": 4, "indoor_outdoor": "indoor", "description": "江边路线的咖啡补给点，热门时段座位不稳定。"},
    {"id": "sh-coffee-009", "name": "静安社区咖啡吧", "category": "coffee", "sub_category": "community_cafe", "district": "静安区", "city": "上海", "address": "上海市静安区昌平路周边", "latitude": 31.2335, "longitude": 121.4519, "price": 33, "visit_duration": 35, "rating": 4.1, "business_hours": "08:30-20:00", "tags": ["咖啡", "社区", "性价比"], "suitable_for": ["独自", "朋友"], "queue_level": 2, "photo_score": 2, "date_score": 2, "food_score": 3, "culture_score": 2, "local_feature_score": 3, "rainy_day_score": 4, "indoor_outdoor": "indoor", "description": "适合作为预算友好路线里的短暂停靠点。"},
    {"id": "sh-food-009", "name": "静安家常本帮小馆", "category": "food", "sub_category": "shanghai_cuisine", "district": "静安区", "city": "上海", "address": "上海市静安区昌平路周边", "latitude": 31.2329, "longitude": 121.4511, "price": 78, "visit_duration": 65, "rating": 4.2, "business_hours": "11:00-21:30", "tags": ["本帮菜", "家常", "朋友"], "suitable_for": ["朋友", "家庭"], "queue_level": 3, "photo_score": 2, "date_score": 2, "food_score": 4, "culture_score": 3, "local_feature_score": 4, "rainy_day_score": 4, "indoor_outdoor": "indoor", "description": "没有强打卡属性，但适合稳定用餐。"},
    {"id": "sh-food-010", "name": "徐汇轻食简餐", "category": "food", "sub_category": "light_meal", "district": "徐汇区", "city": "上海", "address": "上海市徐汇区衡山路周边", "latitude": 31.2027, "longitude": 121.4469, "price": 48, "visit_duration": 45, "rating": 4.1, "business_hours": "10:30-21:00", "tags": ["简餐", "效率", "街区"], "suitable_for": ["独自", "朋友"], "queue_level": 2, "photo_score": 2, "date_score": 2, "food_score": 3, "culture_score": 1, "local_feature_score": 2, "rainy_day_score": 4, "indoor_outdoor": "indoor", "description": "用于控制时间和预算的用餐节点。"},
    {"id": "sh-food-011", "name": "虹口生煎小铺", "category": "food", "sub_category": "shanghai_snacks", "district": "虹口区", "city": "上海", "address": "上海市虹口区四川北路周边", "latitude": 31.2541, "longitude": 121.4866, "price": 32, "visit_duration": 35, "rating": 4.1, "business_hours": "07:00-20:30", "tags": ["生煎", "小吃", "性价比"], "suitable_for": ["独自", "朋友"], "queue_level": 3, "photo_score": 1, "date_score": 1, "food_score": 4, "culture_score": 2, "local_feature_score": 4, "rainy_day_score": 3, "indoor_outdoor": "indoor", "description": "适合北外滩路线穿插的低预算小吃点。"},
    {"id": "sh-food-012", "name": "杨浦夜宵小馆", "category": "food", "sub_category": "night_snack", "district": "杨浦区", "city": "上海", "address": "上海市杨浦区大学路周边", "latitude": 31.3078, "longitude": 121.5131, "price": 55, "visit_duration": 50, "rating": 4.0, "business_hours": "17:00-23:30", "tags": ["夜宵", "朋友", "学生"], "suitable_for": ["朋友", "独自"], "queue_level": 3, "photo_score": 2, "date_score": 2, "food_score": 4, "culture_score": 1, "local_feature_score": 3, "rainy_day_score": 3, "indoor_outdoor": "indoor", "description": "适合杨浦晚间路线，距离市中心路线较远。"},
    {"id": "sh-exhibition-005", "name": "静安小型设计展厅", "category": "exhibition", "sub_category": "design_gallery", "district": "静安区", "city": "上海", "address": "上海市静安区南京西路周边", "latitude": 31.2299, "longitude": 121.4598, "price": 40, "visit_duration": 55, "rating": 4.2, "business_hours": "11:00-19:00", "tags": ["设计", "看展", "室内", "短停"], "suitable_for": ["朋友", "情侣", "独自"], "queue_level": 2, "photo_score": 4, "date_score": 3, "food_score": 1, "culture_score": 4, "local_feature_score": 2, "rainy_day_score": 5, "indoor_outdoor": "indoor", "description": "小体量室内展厅，适合雨天和商圈路线。"},
    {"id": "sh-exhibition-006", "name": "杨浦创意展廊", "category": "exhibition", "sub_category": "creative_gallery", "district": "杨浦区", "city": "上海", "address": "上海市杨浦区大学路周边", "latitude": 31.3062, "longitude": 121.5108, "price": 20, "visit_duration": 50, "rating": 4.1, "business_hours": "10:00-18:00", "tags": ["创意", "展览", "小众"], "suitable_for": ["朋友", "独自"], "queue_level": 1, "photo_score": 3, "date_score": 2, "food_score": 1, "culture_score": 4, "local_feature_score": 3, "rainy_day_score": 4, "indoor_outdoor": "indoor", "description": "用于补充杨浦路线的低成本文化点。"},
    {"id": "sh-museum-004", "name": "上海城市生活馆", "category": "museum", "sub_category": "city_life", "district": "黄浦区", "city": "上海", "address": "上海市黄浦区人民广场周边", "latitude": 31.2321, "longitude": 121.4712, "price": 0, "visit_duration": 70, "rating": 4.3, "business_hours": "09:30-17:30", "tags": ["博物馆", "城市", "室内"], "suitable_for": ["家庭", "独自", "朋友"], "queue_level": 2, "photo_score": 3, "date_score": 2, "food_score": 1, "culture_score": 5, "local_feature_score": 4, "rainy_day_score": 5, "indoor_outdoor": "indoor", "description": "模拟城市生活主题馆，适合文化路线补充。"},
    {"id": "sh-museum-005", "name": "徐汇影像资料馆", "category": "museum", "sub_category": "photo_archive", "district": "徐汇区", "city": "上海", "address": "上海市徐汇区衡山路周边", "latitude": 31.2041, "longitude": 121.4458, "price": 20, "visit_duration": 60, "rating": 4.2, "business_hours": "10:00-17:00", "tags": ["影像", "历史", "室内", "小众"], "suitable_for": ["独自", "朋友"], "queue_level": 1, "photo_score": 4, "date_score": 2, "food_score": 1, "culture_score": 4, "local_feature_score": 3, "rainy_day_score": 5, "indoor_outdoor": "indoor", "description": "偏小众的室内文化点，适合避开热门展馆。"},
    {"id": "sh-street-007", "name": "衡山路安福路街区", "category": "street", "sub_category": "historic_lifestyle", "district": "徐汇区", "city": "上海", "address": "上海市徐汇区衡山路至安福路", "latitude": 31.2108, "longitude": 121.4442, "price": 0, "visit_duration": 65, "rating": 4.5, "business_hours": "10:00-22:00", "tags": ["citywalk", "小店", "咖啡", "拍照"], "suitable_for": ["朋友", "情侣", "独自"], "queue_level": 4, "photo_score": 5, "date_score": 4, "food_score": 3, "culture_score": 4, "local_feature_score": 3, "rainy_day_score": 2, "indoor_outdoor": "outdoor", "description": "氛围强但周末人流明显，适合非高峰时段。"},
    {"id": "sh-street-008", "name": "北外滩滨江步道", "category": "street", "sub_category": "riverside_walk", "district": "虹口区", "city": "上海", "address": "上海市虹口区北外滩滨江", "latitude": 31.2498, "longitude": 121.4979, "price": 0, "visit_duration": 60, "rating": 4.5, "business_hours": "00:00-23:59", "tags": ["江边", "散步", "夜景", "拍照"], "suitable_for": ["情侣", "朋友", "家庭"], "queue_level": 2, "photo_score": 5, "date_score": 4, "food_score": 1, "culture_score": 2, "local_feature_score": 3, "rainy_day_score": 1, "indoor_outdoor": "outdoor", "description": "适合外滩替代视角，天气影响明显。"},
    {"id": "sh-street-009", "name": "昌平路生活街区", "category": "street", "sub_category": "local_street", "district": "静安区", "city": "上海", "address": "上海市静安区昌平路", "latitude": 31.2341, "longitude": 121.4506, "price": 0, "visit_duration": 50, "rating": 4.2, "business_hours": "10:00-22:00", "tags": ["生活街区", "咖啡", "小店"], "suitable_for": ["独自", "朋友"], "queue_level": 2, "photo_score": 3, "date_score": 3, "food_score": 3, "culture_score": 2, "local_feature_score": 4, "rainy_day_score": 2, "indoor_outdoor": "outdoor", "description": "比热门街区更日常，适合偏本地化路线。"},
    {"id": "sh-park-005", "name": "徐汇滨江绿地", "category": "park", "sub_category": "riverside_park", "district": "徐汇区", "city": "上海", "address": "上海市徐汇区龙腾大道周边", "latitude": 31.1845, "longitude": 121.4596, "price": 0, "visit_duration": 60, "rating": 4.6, "business_hours": "06:00-23:00", "tags": ["滨江", "散步", "拍照", "放松"], "suitable_for": ["情侣", "朋友", "家庭"], "queue_level": 2, "photo_score": 4, "date_score": 4, "food_score": 1, "culture_score": 2, "local_feature_score": 3, "rainy_day_score": 1, "indoor_outdoor": "outdoor", "description": "适合和西岸展馆组合，但雨天体验下降。"},
    {"id": "sh-park-006", "name": "杨浦滨江绿地", "category": "park", "sub_category": "riverside_park", "district": "杨浦区", "city": "上海", "address": "上海市杨浦区滨江周边", "latitude": 31.2608, "longitude": 121.5481, "price": 0, "visit_duration": 70, "rating": 4.4, "business_hours": "06:00-22:00", "tags": ["滨江", "工业遗存", "散步"], "suitable_for": ["朋友", "家庭", "独自"], "queue_level": 2, "photo_score": 4, "date_score": 3, "food_score": 1, "culture_score": 3, "local_feature_score": 4, "rainy_day_score": 1, "indoor_outdoor": "outdoor", "description": "适合杨浦方向路线，距离市中心较远。"},
    {"id": "sh-night-005", "name": "北外滩夜景平台", "category": "night", "sub_category": "river_night_view", "district": "虹口区", "city": "上海", "address": "上海市虹口区北外滩周边", "latitude": 31.2495, "longitude": 121.4968, "price": 0, "visit_duration": 45, "rating": 4.6, "business_hours": "18:00-23:59", "tags": ["夜景", "江景", "拍照", "情侣"], "suitable_for": ["情侣", "朋友", "独自"], "queue_level": 3, "photo_score": 5, "date_score": 4, "food_score": 1, "culture_score": 2, "local_feature_score": 3, "rainy_day_score": 1, "indoor_outdoor": "outdoor", "description": "外滩替代夜景点，人流略少但天气影响明显。"},
    {"id": "sh-night-006", "name": "静安寺商圈夜色", "category": "night", "sub_category": "commercial_night", "district": "静安区", "city": "上海", "address": "上海市静安区静安寺周边", "latitude": 31.2232, "longitude": 121.4452, "price": 0, "visit_duration": 40, "rating": 4.3, "business_hours": "18:00-23:00", "tags": ["夜景", "商圈", "短停"], "suitable_for": ["朋友", "情侣"], "queue_level": 3, "photo_score": 4, "date_score": 3, "food_score": 2, "culture_score": 2, "local_feature_score": 2, "rainy_day_score": 2, "indoor_outdoor": "outdoor", "description": "适合商圈路线收尾，地标感中等。"},
    {"id": "sh-shopping-004", "name": "静安室内生活中心", "category": "shopping", "sub_category": "mall", "district": "静安区", "city": "上海", "address": "上海市静安区南京西路周边", "latitude": 31.2291, "longitude": 121.4579, "price": 0, "visit_duration": 70, "rating": 4.3, "business_hours": "10:00-22:00", "tags": ["商场", "室内", "餐饮", "雨天"], "suitable_for": ["朋友", "家庭", "情侣"], "queue_level": 3, "photo_score": 3, "date_score": 3, "food_score": 4, "culture_score": 1, "local_feature_score": 2, "rainy_day_score": 5, "indoor_outdoor": "indoor", "description": "室内功能完整，适合作为雨天兜底。"},
    {"id": "sh-shopping-005", "name": "徐汇社区商业体", "category": "shopping", "sub_category": "neighborhood_mall", "district": "徐汇区", "city": "上海", "address": "上海市徐汇区衡山路周边", "latitude": 31.2021, "longitude": 121.4462, "price": 0, "visit_duration": 55, "rating": 4.0, "business_hours": "10:00-21:30", "tags": ["商场", "室内", "轻逛"], "suitable_for": ["朋友", "家庭"], "queue_level": 2, "photo_score": 2, "date_score": 2, "food_score": 3, "culture_score": 1, "local_feature_score": 2, "rainy_day_score": 5, "indoor_outdoor": "indoor", "description": "不强打卡但稳定，适合控制路线风险。"},
    {"id": "sh-scene-003", "name": "苏州河转角视角", "category": "scene", "sub_category": "urban_view", "district": "静安区", "city": "上海", "address": "上海市静安区苏州河周边", "latitude": 31.2394, "longitude": 121.4621, "price": 0, "visit_duration": 30, "rating": 4.1, "business_hours": "00:00-23:59", "tags": ["苏州河", "城市景观", "短停"], "suitable_for": ["朋友", "独自"], "queue_level": 2, "photo_score": 4, "date_score": 2, "food_score": 1, "culture_score": 3, "local_feature_score": 3, "rainy_day_score": 1, "indoor_outdoor": "outdoor", "description": "适合城市漫步中的短暂停靠，不建议雨天安排。"},
]


THIRD_WAVE_POIS: list[dict[str, Any]] = [
    {"id": "gz-food-009", "name": "陶陶居 第十甫路店", "category": "food", "sub_category": "dim_sum", "district": "荔湾区", "city": "广州", "address": "广州市荔湾区第十甫路", "latitude": 23.1148, "longitude": 113.2498, "price": 98, "visit_duration": 80, "rating": 4.5, "business_hours": "07:30-22:00", "tags": ["早茶", "粤式点心", "老字号", "本地特色"], "suitable_for": ["家庭", "朋友", "情侣"], "queue_level": 4, "photo_score": 2, "date_score": 3, "food_score": 5, "culture_score": 4, "local_feature_score": 5, "rainy_day_score": 4, "indoor_outdoor": "indoor", "description": "适合广州早茶主线的经典老字号，饭点需要预留排队时间。"},
    {"id": "gz-food-010", "name": "广州酒家 文昌路店", "category": "food", "sub_category": "dim_sum", "district": "荔湾区", "city": "广州", "address": "广州市荔湾区文昌南路", "latitude": 23.1194, "longitude": 113.2522, "price": 110, "visit_duration": 85, "rating": 4.6, "business_hours": "08:00-22:30", "tags": ["早茶", "粤菜", "老字号", "聚餐"], "suitable_for": ["家庭", "朋友", "情侣"], "queue_level": 4, "photo_score": 2, "date_score": 3, "food_score": 5, "culture_score": 4, "local_feature_score": 5, "rainy_day_score": 4, "indoor_outdoor": "indoor", "description": "更适合正式一点的广州早茶和正餐衔接，稳定但不便宜。"},
    {"id": "gz-coffee-007", "name": "东山口花园咖啡", "category": "coffee", "sub_category": "neighborhood_cafe", "district": "越秀区", "city": "广州", "address": "广州市越秀区东山口周边", "latitude": 23.1234, "longitude": 113.2991, "price": 42, "visit_duration": 40, "rating": 4.4, "business_hours": "09:00-21:30", "tags": ["咖啡", "洋楼", "拍照", "安静"], "suitable_for": ["情侣", "朋友", "独自"], "queue_level": 2, "photo_score": 4, "date_score": 4, "food_score": 3, "culture_score": 3, "local_feature_score": 4, "rainy_day_score": 4, "indoor_outdoor": "indoor", "description": "东山口风格的轻松停靠点，适合和街区漫步组合。"},
    {"id": "gz-library-002", "name": "广州图书馆", "category": "library", "sub_category": "city_library", "district": "天河区", "city": "广州", "address": "广州市天河区珠江东路", "latitude": 23.1181, "longitude": 113.3296, "price": 0, "visit_duration": 70, "rating": 4.7, "business_hours": "09:00-21:00", "tags": ["图书馆", "室内", "安静", "自习"], "suitable_for": ["独自", "朋友"], "queue_level": 1, "photo_score": 2, "date_score": 3, "food_score": 1, "culture_score": 4, "local_feature_score": 3, "rainy_day_score": 5, "indoor_outdoor": "indoor", "description": "适合安静路线和雨天兜底，也能作为节奏缓冲点。"},
    {"id": "gz-museum-003", "name": "广东省博物馆", "category": "museum", "sub_category": "history_museum", "district": "天河区", "city": "广州", "address": "广州市天河区珠江新城", "latitude": 23.1175, "longitude": 113.3217, "price": 0, "visit_duration": 110, "rating": 4.7, "business_hours": "09:00-17:00", "tags": ["博物馆", "历史", "室内", "展览"], "suitable_for": ["家庭", "独自", "朋友"], "queue_level": 3, "photo_score": 3, "date_score": 3, "food_score": 1, "culture_score": 5, "local_feature_score": 4, "rainy_day_score": 5, "indoor_outdoor": "indoor", "description": "广州文化路线里的稳妥主站，适合拉长停留时间。"},
    {"id": "gz-street-010", "name": "沙面慢行街区", "category": "street", "sub_category": "historic_block", "district": "荔湾区", "city": "广州", "address": "广州市荔湾区沙面岛", "latitude": 23.1118, "longitude": 113.2412, "price": 0, "visit_duration": 65, "rating": 4.6, "business_hours": "00:00-23:59", "tags": ["街区", "拍照", "洋楼", "citywalk"], "suitable_for": ["情侣", "朋友", "独自"], "queue_level": 2, "photo_score": 5, "date_score": 4, "food_score": 2, "culture_score": 4, "local_feature_score": 5, "rainy_day_score": 2, "indoor_outdoor": "outdoor", "description": "经典老广州街区，适合慢走和拍照，但天气影响明显。"},
    {"id": "gz-park-007", "name": "二沙岛艺术公园", "category": "park", "sub_category": "urban_park", "district": "越秀区", "city": "广州", "address": "广州市越秀区二沙岛", "latitude": 23.1139, "longitude": 113.3073, "price": 0, "visit_duration": 55, "rating": 4.5, "business_hours": "06:00-22:30", "tags": ["公园", "艺术", "散步", "江边"], "suitable_for": ["家庭", "情侣", "独自"], "queue_level": 1, "photo_score": 4, "date_score": 4, "food_score": 1, "culture_score": 2, "local_feature_score": 4, "rainy_day_score": 1, "indoor_outdoor": "outdoor", "description": "适合把路线从热闹商圈拉回到更松弛的节奏。"},
    {"id": "gz-night-007", "name": "珠江新城灯光步道", "category": "night", "sub_category": "urban_night_walk", "district": "天河区", "city": "广州", "address": "广州市天河区珠江新城", "latitude": 23.1202, "longitude": 113.3221, "price": 0, "visit_duration": 40, "rating": 4.4, "business_hours": "18:00-23:30", "tags": ["夜景", "散步", "地标", "拍照"], "suitable_for": ["情侣", "朋友", "家庭"], "queue_level": 3, "photo_score": 5, "date_score": 4, "food_score": 1, "culture_score": 2, "local_feature_score": 4, "rainy_day_score": 1, "indoor_outdoor": "outdoor", "description": "适合作为广州夜游收尾节点，路线收束感强。"},
    {"id": "gz-shopping-006", "name": "天环广场", "category": "shopping", "sub_category": "mall", "district": "天河区", "city": "广州", "address": "广州市天河区天河路218号", "latitude": 23.1338, "longitude": 113.3279, "price": 0, "visit_duration": 70, "rating": 4.5, "business_hours": "10:00-22:00", "tags": ["商场", "餐饮", "室内", "高端"], "suitable_for": ["情侣", "朋友", "家庭"], "queue_level": 3, "photo_score": 4, "date_score": 4, "food_score": 4, "culture_score": 1, "local_feature_score": 2, "rainy_day_score": 5, "indoor_outdoor": "indoor", "description": "珠江新城和天河商圈的高质量室内兜底点。"},
    {"id": "sh-food-013", "name": "南翔馒头店 豫园店", "category": "food", "sub_category": "shanghai_snacks", "district": "黄浦区", "city": "上海", "address": "上海市黄浦区豫园周边", "latitude": 31.2279, "longitude": 121.4922, "price": 45, "visit_duration": 40, "rating": 4.3, "business_hours": "08:00-20:30", "tags": ["小笼", "本地小吃", "热门"], "suitable_for": ["独自", "朋友", "家庭"], "queue_level": 4, "photo_score": 3, "date_score": 2, "food_score": 5, "culture_score": 3, "local_feature_score": 5, "rainy_day_score": 3, "indoor_outdoor": "indoor", "description": "豫园附近的经典小笼节点，适合早起衔接。"},
    {"id": "sh-food-014", "name": "大富贵酒楼 西藏南路店", "category": "food", "sub_category": "shanghai_cuisine", "district": "黄浦区", "city": "上海", "address": "上海市黄浦区西藏南路", "latitude": 31.2176, "longitude": 121.4851, "price": 88, "visit_duration": 70, "rating": 4.2, "business_hours": "07:00-21:30", "tags": ["本帮菜", "早饭", "老牌", "正餐"], "suitable_for": ["家庭", "朋友", "情侣"], "queue_level": 3, "photo_score": 2, "date_score": 3, "food_score": 5, "culture_score": 3, "local_feature_score": 4, "rainy_day_score": 4, "indoor_outdoor": "indoor", "description": "适合把早餐、早茶和正式用餐三种需求压在一个稳定节点里。"},
    {"id": "sh-coffee-010", "name": "永康路街角咖啡", "category": "coffee", "sub_category": "street_cafe", "district": "徐汇区", "city": "上海", "address": "上海市徐汇区永康路周边", "latitude": 31.2051, "longitude": 121.4476, "price": 40, "visit_duration": 35, "rating": 4.3, "business_hours": "09:00-21:00", "tags": ["咖啡", "街区", "拍照", "松弛"], "suitable_for": ["情侣", "朋友", "独自"], "queue_level": 2, "photo_score": 4, "date_score": 4, "food_score": 3, "culture_score": 2, "local_feature_score": 3, "rainy_day_score": 4, "indoor_outdoor": "indoor", "description": "徐汇街区里的轻咖啡点，适合缓冲节奏。"},
    {"id": "sh-library-002", "name": "上海图书馆东馆", "category": "library", "sub_category": "city_library", "district": "浦东新区", "city": "上海", "address": "上海市浦东新区世纪大道", "latitude": 31.2268, "longitude": 121.5339, "price": 0, "visit_duration": 80, "rating": 4.8, "business_hours": "09:00-21:00", "tags": ["图书馆", "室内", "安静", "学习"], "suitable_for": ["独自", "朋友"], "queue_level": 1, "photo_score": 3, "date_score": 3, "food_score": 1, "culture_score": 4, "local_feature_score": 3, "rainy_day_score": 5, "indoor_outdoor": "indoor", "description": "适合安静、低预算和雨天路线，也能作为长停点。"},
    {"id": "sh-museum-006", "name": "上海当代艺术博物馆", "category": "museum", "sub_category": "art_museum", "district": "黄浦区", "city": "上海", "address": "上海市黄浦区花园港路200号", "latitude": 31.2182, "longitude": 121.4859, "price": 60, "visit_duration": 90, "rating": 4.5, "business_hours": "10:00-18:00", "tags": ["当代艺术", "室内", "看展"], "suitable_for": ["朋友", "情侣", "独自"], "queue_level": 2, "photo_score": 4, "date_score": 3, "food_score": 1, "culture_score": 5, "local_feature_score": 3, "rainy_day_score": 5, "indoor_outdoor": "indoor", "description": "适合文化向路线补强，内容和空间感都比较稳定。"},
    {"id": "sh-street-010", "name": "武康路安福路晨走街区", "category": "street", "sub_category": "historic_lifestyle", "district": "徐汇区", "city": "上海", "address": "上海市徐汇区武康路至安福路", "latitude": 31.2097, "longitude": 121.4451, "price": 0, "visit_duration": 60, "rating": 4.7, "business_hours": "08:00-22:00", "tags": ["citywalk", "咖啡", "洋楼", "拍照"], "suitable_for": ["情侣", "朋友", "独自"], "queue_level": 4, "photo_score": 5, "date_score": 4, "food_score": 3, "culture_score": 4, "local_feature_score": 3, "rainy_day_score": 2, "indoor_outdoor": "outdoor", "description": "上海最典型的生活方式街区之一，适合早些时段安排。"},
    {"id": "sh-park-007", "name": "世纪公园", "category": "park", "sub_category": "urban_park", "district": "浦东新区", "city": "上海", "address": "上海市浦东新区锦绣路1001号", "latitude": 31.2176, "longitude": 121.5581, "price": 10, "visit_duration": 90, "rating": 4.5, "business_hours": "07:00-17:00", "tags": ["公园", "亲子", "散步", "自然"], "suitable_for": ["家庭", "朋友", "独自"], "queue_level": 1, "photo_score": 3, "date_score": 4, "food_score": 1, "culture_score": 1, "local_feature_score": 2, "rainy_day_score": 1, "indoor_outdoor": "outdoor", "description": "更偏放松和亲子，适合做大行程中的缓冲段。"},
    {"id": "sh-night-007", "name": "外滩观景平台", "category": "night", "sub_category": "landmark_night_view", "district": "黄浦区", "city": "上海", "address": "上海市黄浦区中山东一路", "latitude": 31.2382, "longitude": 121.4904, "price": 0, "visit_duration": 50, "rating": 4.8, "business_hours": "18:00-23:59", "tags": ["夜景", "外滩", "地标", "拍照"], "suitable_for": ["情侣", "朋友", "家庭"], "queue_level": 4, "photo_score": 5, "date_score": 4, "food_score": 1, "culture_score": 2, "local_feature_score": 5, "rainy_day_score": 1, "indoor_outdoor": "outdoor", "description": "上海经典夜景主站，适合路线收尾但拥挤度较高。"},
    {"id": "sh-shopping-006", "name": "静安嘉里中心", "category": "shopping", "sub_category": "mall", "district": "静安区", "city": "上海", "address": "上海市静安区南京西路", "latitude": 31.2292, "longitude": 121.4546, "price": 0, "visit_duration": 70, "rating": 4.5, "business_hours": "10:00-22:00", "tags": ["商场", "餐饮", "室内", "品质"], "suitable_for": ["情侣", "朋友", "家庭"], "queue_level": 3, "photo_score": 4, "date_score": 4, "food_score": 4, "culture_score": 1, "local_feature_score": 2, "rainy_day_score": 5, "indoor_outdoor": "indoor", "description": "静安商圈里比较稳的高质量室内节点，适合兜底。"},
]


FOURTH_WAVE_POIS: list[dict[str, Any]] = [
    {"id": "gz-food-011", "name": "银记肠粉 上下九店", "category": "food", "sub_category": "local_snack", "district": "荔湾区", "city": "广州", "address": "广州市荔湾区上下九周边", "latitude": 23.1140, "longitude": 113.2474, "price": 24, "visit_duration": 25, "rating": 4.2, "business_hours": "07:00-21:30", "tags": ["肠粉", "小吃", "早饭", "本地味"], "suitable_for": ["独自", "朋友"], "queue_level": 3, "photo_score": 1, "date_score": 2, "food_score": 4, "culture_score": 3, "local_feature_score": 5, "rainy_day_score": 3, "indoor_outdoor": "indoor", "description": "适合早饭或中途垫肚子的本地小吃节点。"},
    {"id": "gz-food-012", "name": "泮溪酒家", "category": "food", "sub_category": "dim_sum", "district": "荔湾区", "city": "广州", "address": "广州市荔湾区龙津西路", "latitude": 23.1281, "longitude": 113.2458, "price": 95, "visit_duration": 85, "rating": 4.4, "business_hours": "08:00-21:30", "tags": ["早茶", "粤菜", "老字号", "园林"], "suitable_for": ["家庭", "朋友", "情侣"], "queue_level": 3, "photo_score": 3, "date_score": 4, "food_score": 5, "culture_score": 4, "local_feature_score": 5, "rainy_day_score": 4, "indoor_outdoor": "indoor", "description": "更偏园林和老广州气质的早茶点，适合文化路线。"},
    {"id": "gz-coffee-008", "name": "珠江新城落地窗咖啡", "category": "coffee", "sub_category": "river_cafe", "district": "天河区", "city": "广州", "address": "广州市天河区珠江新城周边", "latitude": 23.1189, "longitude": 113.3261, "price": 48, "visit_duration": 40, "rating": 4.5, "business_hours": "09:00-22:00", "tags": ["咖啡", "景观", "拍照", "约会"], "suitable_for": ["情侣", "朋友", "独自"], "queue_level": 3, "photo_score": 5, "date_score": 4, "food_score": 3, "culture_score": 2, "local_feature_score": 3, "rainy_day_score": 4, "indoor_outdoor": "indoor", "description": "珠江新城的景观型咖啡点，适合轻松约会路线。"},
    {"id": "gz-coffee-009", "name": "西关老宅咖啡", "category": "coffee", "sub_category": "historic_cafe", "district": "荔湾区", "city": "广州", "address": "广州市荔湾区恩宁路周边", "latitude": 23.1130, "longitude": 113.2447, "price": 36, "visit_duration": 35, "rating": 4.2, "business_hours": "09:30-20:30", "tags": ["咖啡", "西关", "老宅", "拍照"], "suitable_for": ["朋友", "情侣", "独自"], "queue_level": 2, "photo_score": 4, "date_score": 4, "food_score": 3, "culture_score": 4, "local_feature_score": 5, "rainy_day_score": 3, "indoor_outdoor": "indoor", "description": "适合和恩宁路、永庆坊类街区组合。"},
    {"id": "gz-museum-004", "name": "广东民间工艺博物馆", "category": "museum", "sub_category": "folk_art_museum", "district": "荔湾区", "city": "广州", "address": "广州市荔湾区中山七路恩龙里34号", "latitude": 23.1271, "longitude": 113.2484, "price": 10, "visit_duration": 75, "rating": 4.4, "business_hours": "09:00-17:30", "tags": ["博物馆", "工艺", "文化", "室内"], "suitable_for": ["独自", "朋友", "家庭"], "queue_level": 1, "photo_score": 3, "date_score": 3, "food_score": 1, "culture_score": 5, "local_feature_score": 5, "rainy_day_score": 5, "indoor_outdoor": "indoor", "description": "更偏岭南细分文化的博物馆点，适合深度文化线。"},
    {"id": "gz-exhibition-006", "name": "红专厂创意园", "category": "exhibition", "sub_category": "creative_park", "district": "天河区", "city": "广州", "address": "广州市天河区员村周边", "latitude": 23.1147, "longitude": 113.3540, "price": 0, "visit_duration": 70, "rating": 4.3, "business_hours": "10:00-22:00", "tags": ["创意园", "拍照", "街区", "咖啡"], "suitable_for": ["朋友", "情侣", "独自"], "queue_level": 2, "photo_score": 4, "date_score": 3, "food_score": 2, "culture_score": 3, "local_feature_score": 3, "rainy_day_score": 2, "indoor_outdoor": "outdoor", "description": "更偏老牌创意园质感，适合和天河片区组合。"},
    {"id": "gz-street-011", "name": "永庆坊", "category": "street", "sub_category": "historic_lifestyle", "district": "荔湾区", "city": "广州", "address": "广州市荔湾区恩宁路", "latitude": 23.1174, "longitude": 113.2451, "price": 0, "visit_duration": 70, "rating": 4.6, "business_hours": "00:00-23:59", "tags": ["街区", "西关", "拍照", "老城"], "suitable_for": ["情侣", "朋友", "独自"], "queue_level": 4, "photo_score": 5, "date_score": 4, "food_score": 3, "culture_score": 5, "local_feature_score": 5, "rainy_day_score": 2, "indoor_outdoor": "outdoor", "description": "广州老城里最经典的生活方式街区之一。"},
    {"id": "gz-park-008", "name": "流花湖公园", "category": "park", "sub_category": "urban_park", "district": "越秀区", "city": "广州", "address": "广州市越秀区流花路周边", "latitude": 23.1448, "longitude": 113.2568, "price": 0, "visit_duration": 60, "rating": 4.3, "business_hours": "06:00-22:00", "tags": ["公园", "散步", "湖景", "安静"], "suitable_for": ["家庭", "情侣", "独自"], "queue_level": 1, "photo_score": 3, "date_score": 4, "food_score": 1, "culture_score": 1, "local_feature_score": 2, "rainy_day_score": 1, "indoor_outdoor": "outdoor", "description": "适合做中段降速和补体力的公园点。"},
    {"id": "gz-night-008", "name": "江边夜跑绿道", "category": "night", "sub_category": "river_night_walk", "district": "海珠区", "city": "广州", "address": "广州市海珠区珠江沿线", "latitude": 23.1080, "longitude": 113.3015, "price": 0, "visit_duration": 35, "rating": 4.2, "business_hours": "18:00-23:59", "tags": ["夜景", "散步", "江边", "轻松"], "suitable_for": ["朋友", "情侣", "独自"], "queue_level": 2, "photo_score": 4, "date_score": 3, "food_score": 1, "culture_score": 1, "local_feature_score": 3, "rainy_day_score": 1, "indoor_outdoor": "outdoor", "description": "比打卡夜景更松弛的夜间散步节点。"},
    {"id": "gz-shopping-007", "name": "万菱汇", "category": "shopping", "sub_category": "mall", "district": "天河区", "city": "广州", "address": "广州市天河区天河路230号", "latitude": 23.1325, "longitude": 113.3290, "price": 0, "visit_duration": 60, "rating": 4.2, "business_hours": "10:00-22:00", "tags": ["商场", "餐饮", "室内", "轻松"], "suitable_for": ["朋友", "情侣", "家庭"], "queue_level": 3, "photo_score": 3, "date_score": 3, "food_score": 3, "culture_score": 1, "local_feature_score": 2, "rainy_day_score": 5, "indoor_outdoor": "indoor", "description": "天河路商圈里功能型较强的兜底点。"},
    {"id": "sh-food-015", "name": "鲜得来 排骨年糕", "category": "food", "sub_category": "shanghai_snacks", "district": "黄浦区", "city": "上海", "address": "上海市黄浦区南京东路周边", "latitude": 31.2364, "longitude": 121.4788, "price": 35, "visit_duration": 35, "rating": 4.1, "business_hours": "08:00-20:30", "tags": ["小吃", "本地味", "性价比"], "suitable_for": ["独自", "朋友"], "queue_level": 3, "photo_score": 1, "date_score": 2, "food_score": 4, "culture_score": 3, "local_feature_score": 5, "rainy_day_score": 3, "indoor_outdoor": "indoor", "description": "适合上海老城短停的小吃节点。"},
    {"id": "sh-food-016", "name": "荣小馆", "category": "food", "sub_category": "shanghai_cuisine", "district": "徐汇区", "city": "上海", "address": "上海市徐汇区复兴西路周边", "latitude": 31.2088, "longitude": 121.4504, "price": 105, "visit_duration": 80, "rating": 4.4, "business_hours": "11:00-21:30", "tags": ["本帮菜", "约会", "小馆"], "suitable_for": ["情侣", "朋友", "家庭"], "queue_level": 3, "photo_score": 3, "date_score": 4, "food_score": 5, "culture_score": 3, "local_feature_score": 3, "rainy_day_score": 4, "indoor_outdoor": "indoor", "description": "更稳的本帮菜小馆，适合中晚餐衔接。"},
    {"id": "sh-coffee-011", "name": "苏州河河畔咖啡", "category": "coffee", "sub_category": "river_cafe", "district": "静安区", "city": "上海", "address": "上海市静安区苏州河沿线", "latitude": 31.2413, "longitude": 121.4618, "price": 44, "visit_duration": 40, "rating": 4.3, "business_hours": "09:00-21:00", "tags": ["咖啡", "河景", "拍照"], "suitable_for": ["朋友", "情侣", "独自"], "queue_level": 2, "photo_score": 4, "date_score": 4, "food_score": 3, "culture_score": 2, "local_feature_score": 2, "rainy_day_score": 4, "indoor_outdoor": "indoor", "description": "适合苏州河沿线的中段补给。"},
    {"id": "sh-coffee-012", "name": "豫园边上茶咖", "category": "coffee", "sub_category": "street_cafe", "district": "黄浦区", "city": "上海", "address": "上海市黄浦区豫园周边", "latitude": 31.2285, "longitude": 121.4930, "price": 52, "visit_duration": 35, "rating": 4.2, "business_hours": "09:30-21:00", "tags": ["咖啡", "茶饮", "拍照", "街区"], "suitable_for": ["情侣", "朋友", "独自"], "queue_level": 3, "photo_score": 4, "date_score": 4, "food_score": 3, "culture_score": 3, "local_feature_score": 4, "rainy_day_score": 4, "indoor_outdoor": "indoor", "description": "适合把豫园周边路线做得更轻松一点。"},
    {"id": "sh-museum-007", "name": "上海邮政博物馆", "category": "museum", "sub_category": "history_museum", "district": "虹口区", "city": "上海", "address": "上海市虹口区北苏州路", "latitude": 31.2435, "longitude": 121.4916, "price": 15, "visit_duration": 60, "rating": 4.3, "business_hours": "09:00-17:00", "tags": ["历史", "建筑", "室内"], "suitable_for": ["独自", "朋友", "家庭"], "queue_level": 1, "photo_score": 4, "date_score": 2, "food_score": 1, "culture_score": 4, "local_feature_score": 4, "rainy_day_score": 5, "indoor_outdoor": "indoor", "description": "适合外滩北段或北外滩路线补充文化厚度。"},
    {"id": "sh-exhibition-007", "name": "余德耀美术馆", "category": "exhibition", "sub_category": "art_museum", "district": "徐汇区", "city": "上海", "address": "上海市徐汇区龙腾大道", "latitude": 31.1877, "longitude": 121.4621, "price": 80, "visit_duration": 90, "rating": 4.4, "business_hours": "10:00-21:00", "tags": ["看展", "艺术", "西岸"], "suitable_for": ["朋友", "情侣", "独自"], "queue_level": 2, "photo_score": 4, "date_score": 4, "food_score": 1, "culture_score": 5, "local_feature_score": 3, "rainy_day_score": 5, "indoor_outdoor": "indoor", "description": "和西岸方向组合很自然的展览节点。"},
    {"id": "sh-street-011", "name": "愚园路生活街区", "category": "street", "sub_category": "historic_lifestyle", "district": "长宁区", "city": "上海", "address": "上海市长宁区愚园路", "latitude": 31.2198, "longitude": 121.4305, "price": 0, "visit_duration": 55, "rating": 4.5, "business_hours": "10:00-22:00", "tags": ["街区", "咖啡", "小店", "citywalk"], "suitable_for": ["朋友", "情侣", "独自"], "queue_level": 3, "photo_score": 4, "date_score": 4, "food_score": 3, "culture_score": 4, "local_feature_score": 3, "rainy_day_score": 2, "indoor_outdoor": "outdoor", "description": "长宁偏生活方式的一条街，适合做轻松版 citywalk。"},
    {"id": "sh-park-008", "name": "徐家汇公园", "category": "park", "sub_category": "urban_park", "district": "徐汇区", "city": "上海", "address": "上海市徐汇区肇嘉浜路周边", "latitude": 31.1945, "longitude": 121.4464, "price": 0, "visit_duration": 45, "rating": 4.2, "business_hours": "06:00-22:00", "tags": ["公园", "散步", "市中心"], "suitable_for": ["朋友", "家庭", "独自"], "queue_level": 1, "photo_score": 3, "date_score": 3, "food_score": 1, "culture_score": 1, "local_feature_score": 2, "rainy_day_score": 1, "indoor_outdoor": "outdoor", "description": "市中心轻量降速点，适合路线中段放松。"},
    {"id": "sh-night-008", "name": "苏州河夜游栈道", "category": "night", "sub_category": "river_night_walk", "district": "静安区", "city": "上海", "address": "上海市静安区苏州河沿线", "latitude": 31.2399, "longitude": 121.4628, "price": 0, "visit_duration": 40, "rating": 4.3, "business_hours": "18:00-23:30", "tags": ["夜景", "散步", "河岸"], "suitable_for": ["朋友", "情侣", "独自"], "queue_level": 2, "photo_score": 4, "date_score": 4, "food_score": 1, "culture_score": 2, "local_feature_score": 2, "rainy_day_score": 1, "indoor_outdoor": "outdoor", "description": "比外滩更轻松的夜游线路，适合慢走。"},
    {"id": "sh-shopping-007", "name": "环贸 iapm", "category": "shopping", "sub_category": "mall", "district": "徐汇区", "city": "上海", "address": "上海市徐汇区淮海中路999号", "latitude": 31.2195, "longitude": 121.4603, "price": 0, "visit_duration": 70, "rating": 4.5, "business_hours": "10:00-22:00", "tags": ["商场", "餐饮", "室内", "高端"], "suitable_for": ["情侣", "朋友", "家庭"], "queue_level": 3, "photo_score": 4, "date_score": 4, "food_score": 4, "culture_score": 1, "local_feature_score": 2, "rainy_day_score": 5, "indoor_outdoor": "indoor", "description": "淮海路商圈里的高质量室内节点。"},
]


def load_pois(path: Path) -> list[dict[str, Any]]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise ValueError("POI file must contain a JSON list.")
    return [dict(item) for item in data if isinstance(item, dict)]


def save_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def merge_pois(existing: list[dict[str, Any]], additions: list[dict[str, Any]]) -> list[dict[str, Any]]:
    by_id = {str(item.get("id")): dict(item) for item in existing if item.get("id")}
    for item in additions:
        by_id[str(item["id"])] = dict(item)
    seen: set[str] = set()
    merged: list[dict[str, Any]] = []
    for item in [*existing, *additions]:
        poi_id = str(item.get("id"))
        if not poi_id or poi_id in seen:
            continue
        seen.add(poi_id)
        merged.append(by_id[poi_id])
    return merged


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Append curated local demo POIs.")
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_INPUT)
    return parser


def main() -> int:
    args = build_parser().parse_args()
    existing = load_pois(args.input)
    additions = [*ADDITIONAL_POIS, *SECOND_WAVE_POIS, *THIRD_WAVE_POIS, *FOURTH_WAVE_POIS]
    merged = merge_pois(existing, additions)
    save_json(args.output, merged)
    print(json.dumps({"input": str(args.input), "output": str(args.output), "before": len(existing), "after": len(merged), "added_or_updated": len(additions)}, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
